---

- name: Provision a {{ application_directory }} db server
  hosts: dbservers
  sudo: yes
  sudo_user: root
  remote_user: "{{remoteu}}"
  vars:
    - update_apt_cache: yes
  vars_files:
    - env_vars/{{ env }}.yml
    - ./pass_ex.yml # always use last
    - ../pass.yml # always use last

  roles:
#    - safe
    - pip
    - base
    - db
