---

- name: Provision a {{ application_directory }} web server
  hosts: webservers
  sudo: yes
  sudo_user: root
  remote_user: "{{remoteu}}"
  vars:
    - update_apt_cache: yes
  vars_files:
    - env_vars/{{ env }}.yml
    - ./pass_ex.yml 
    - ../pass.yml # always use last


  roles:
#    - safe
    - pip
    - base
    - web
