---

- name: restart application
  supervisorctl: name={{ application_directory }} state=restarted
  tags: reload

- name: restart nginx
  service: name=nginx state=restarted enabled=yes
  tags: reload

- name: reload nginx
  service: name=nginx state=reloaded
  tags: reload
