---

- name: Create the Supervisor config file
  template: src=supervisor_config.j2
            dest=/etc/supervisor/conf.d/{{ application_directory }}.conf
            backup=yes
  tags: sup

- name: Re-read the Supervisor config files
  supervisorctl: name={{ application_directory }} state=present
  tags: sup

- name: Restart Supervisor
  supervisorctl: name={{ application_directory }} state=restarted
  tags: sup
